spring:

  datasource:
    url: jdbc:mysql://localhost:3306/lifecalc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: bobodrool
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: bobodrool


  redis:
    password: bobodrool
    host: localhost


server:
  port: 80

swagger:
  enable: true